name: .NET 10 Android Build
on:
  workflow_dispatch:
    inputs:
      maui-branch:
        required: true
        type: string
        default: "develop"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 10.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Display .NET version
        run: dotnet --version

      - name: Print runner image version
        run: cat /etc/image-release || echo "Image version info not found"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Run Android build
        run: dotnet build -t:Build -f:net10.0-android
